name: e_document_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+4
# after change version don't forget to run command below
### dart generate_version.dart ###

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  dio: ^5.3.3
  touch_ripple_effect: ^2.3.0
  font_awesome_flutter: ^10.5.0
  flutter_svg: ^2.0.7
  calendar_date_picker2: ^0.5.3
  either_dart: ^1.0.0
  loading_indicator: ^3.1.1
  get_storage: ^2.1.1
  upgrader: ^8.1.0
  encrypt: ^5.0.3
  pointycastle: ^3.7.3
  crypto: ^3.0.3
  device_info_plus: ^9.1.0
  safe_device: ^1.1.4
  package_info_plus: ^4.2.0
  intl: ^0.18.1
  awesome_select: ^6.0.0
  flutter_pdfview: ^1.3.2
  http: ^0.13.6
  path_provider: ^2.1.1
  path: ^1.8.3
  date_format: ^2.0.7
  flutter_easyloading: ^3.0.5
  permission_handler: ^11.0.1
  blur: ^3.1.0
  yaml: ^3.1.2
  firebase_core: ^2.17.0
  firebase_messaging: ^14.6.9
  overlay_support: ^2.1.0
  badges: ^3.1.2
  flutter_local_notifications: ^16.1.0
  get_time_ago: ^1.2.5
  flutter_launcher_icons: ^0.13.1
  custom_refresh_indicator: ^3.0.0
  flutter_profile_picture: ^2.0.0
  internet_connection_checker: ^1.0.0+1
  open_file: ^3.3.2
  open_file_manager: ^0.0.4
  lecle_downloads_path_provider: ^0.0.2+8
  file_picker: ^6.1.1
  file_manager: ^1.0.2

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  image_path: "assets/icons/app_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

  image_path_android: "assets/icons/app_logo.png"
  image_path_ios: "assets/icons/app_logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/